package_rename_config:
  android:
    app_name: LifeQue
    package_name: com.programmernexus.lifeque
    override_old_package: com.programmernexus.remindme

  ios:
    app_name: LifeQue
    bundle_name: LifeQue
    package_name: com.programmernexus.lifeque

  linux:
    app_name: LifeQue
    package_name: com.programmernexus.lifeque

  macos:
    app_name: LifeQue
    package_name: com.programmernexus.lifeque

  web:
    app_name: LifeQue
    short_app_name: LifeQue
    description: Smart Task & Reminder Manager

  windows:
    app_name: LifeQue
    organization: ProgrammerNexus
    copyright_notice: © 2025 ProgrammerNexus
